version: '3'
services:
  nginx:
    image:
      nginx:latest
    ports:
      - "80:80"
    volumes:
      - code:/code
      - ./front-nginx/html:/usr/share/nginx/html
      - nginx:/etc/nginx.conf.d      
    depends_on:
      - front-nginx
  front-nginx:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn backend.wsqi.application --bind 0.0.0.0:8000
    volumes:
      - .:/code
    expose:
      - "8000"